### ISSUE TITLE
Searching in enhanced dependencies

### ISSUE THREAD

**Issue by bguil** [grew-nlp/grew#1]
Report for the [message in UD issue](https://github.com/UniversalDependencies/docs/issues/812#issuecomment-924488398) from @arademaker:

> can we search in the enhanced dependencies graph using grew?

**Comment by arademaker** [comment]
For instance, it would be nice to search in the UD Deep treebanks. Patterns like:

https://ufal.mff.cuni.cz/deep-universal-dependencies/deep-ud-stats-external-subjects

**Comment by bguil** [comment]
There are several ways to deal with enhanced dependencies:

 * For corpora where enhanced dependencies are available, in Grew-match, there is a switch EUD / UD where you can chose to search in all dependencies (EUD) or only in the basic UD layer.
 * If you use the EUD flag, you can make a direct reference to an enhanced relation with the prefix `E:`. For instance:
  `pattern { N1 -[E:nsubj]-> N2 }` (see in [GM](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=614afcc259d49&eud=yes)).
 * For more complex requests, please refer to [doc](https://grew.fr/doc/graph/#edges) where the encoding of edges is explained. A few examples:
    * Search for an enhanced relation without basic counterpart: [GM](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=614b11f0c1a9d&eud=yes)
    * Count the frequencies of subtypes for enhanced `nmod` relation: [GM](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=614b12a1239ac&clustering=e.2&eud=yes)
 * For empty nodes on EUD, see the following example: [GM](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=614b14e75a4f0&clustering=N.upos&eud=yes) search for empty nodes and clustering by `upos`

**Comment by bguil** [comment]
Regarding Deep Universal Dependencies, it is a different project and the corresponding corpora are not currently available in Grew-match.
It would be probably quite easy to add them, but I would like to prevent the inflation of the number of corpora!

**Comment by arademaker** [comment]
> It would be probably quite easy to add them, but I would like to prevent the inflation of the number of corpora!

I see. I will try to install grew locally. Any idea of how difficult would be to create a docker?

**Comment by bguil** [comment]
I don't have enough experience with docker to answer. I open another issue #3 about this.
