### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by nschneid** [grew-nlp/grew#10]
Searching just-updated UD_English-EWT:

An BUG occurred, please report
"Libgrew.Libgrew.Bug(\"[Libgrew.Corpus.load_corpus_opt] UNCAUGHT EXCEPTION: End_of_file\")"

**Comment by bguil** [comment]
I guess that it may be linked to the fact that you send a request just after an update, before the compilation of the corpus is finished.

I'll try to reproduce it locally.

**Comment by bguil** [comment]
I confirm my guess. You were very unlucky to request just at the moment the corpus was updated on the server.

I have added a more friendly error message [here](https://gitlab.inria.fr/grew/grew_match_back/-/commit/dfbf0b64805dc7d2ecac7517d37c83936594e05f).

**Comment by nschneid** [comment]
Thanks
