### ISSUE TITLE
Romanian RRT

### ISSUE THREAD

**Issue by samo-g** [grew-nlp/grew#11]
Quering the Romanian RRT Ud treebank, I find the following message:

An BUG occurred, please report
"Libgrew.Libgrew.Bug(\"[Libgrew.Corpus.load_corpus_opt] UNCAUGHT EXCEPTION: (Failure \\\"input_value: truncated object\\\")\")"

**Comment by bguil** [comment]
This is now fixed. Thanks for reporting.

**Comment by samo-g** [comment]
Thank you so much for your precious work and help!
