### ISSUE TITLE
Bug with UD_German-HDT@2.10

### ISSUE THREAD

**Issue by kaiserkueche** [grew-nlp/grew#15]
Hello,

Since the new version `2.10`, the `UD_German-HDT@2.10` corpus doesn't work anymore. Each time I try to search something, it prints this issue:

```
"Libgrew.Libgrew.Bug(\"[Libgrew.Corpus.load_corpus_opt] UNCAUGHT EXCEPTION: End_of_file\")"
```

Thank you for the correction.

**Comment by bguil** [comment]
Thanks for reporting!
I have issues with the size of the treebank. I'm trying to fix this ASAP and I comment again on the issue when it's fixed.
Sorry for the delay.

**Comment by bguil** [comment]
Fixed!
