### ISSUE TITLE
small bug with double clustering

### ISSUE THREAD

**Issue by sylvainkahane** [grew-nlp/grew#18]
quand on fait une première requête avec double clustering, tout se passe bien.
Si on modifie un des deux champs cluster et qu'on relance, c'est encore ok.
Si on refait ça et qu'on relance, la page ne se rafraichit pas. En cliquand sur les résultats, elle se refraichit.
J'ai testé sur Firefox et Chrome plusieurs fois et ça le fait à chaque fois.
C'est pas génant, mais assez surprenant.

**Comment by bguil** [comment]
This should be fixed new (be sure to enforce page reloading).
Please re-open if you still have the problem
