### ISSUE TITLE
viewing dependency-FTB without the anonymization

### ISSUE THREAD

**Issue by jthale76** [grew-nlp/grew#2]
I have an academic license from Anne Abeillé for the FTB itself, i.e. the original annotations. Is there a straightforward way to invoke that license in order to view the tokens of the dependency FTB on match.grew.fr? or would I need to rerun the pipeline and view it on my own local instance of the search tool?

**Comment by bguil** [comment]
Unfortunately, I cannot see a sensible way to give access to the full annotations. I would have to check the fact that you have this licence but Grew-match is completely open without account managing.

I think that you have to use a local  installation, following https://grew.fr/grew_match/install/.

**Comment by jthale76** [comment]
local installation works great! thanks!
