### ISSUE TITLE
trouble setting up local installation

### ISSUE THREAD

**Issue by jthale76** [grew-nlp/grew#20]
I'm a long-time grew fan trying to set up a local installation on macOS Big Sur 11.6.8

when I get to installing the backend in Step 3 of the [instructions](https://grew.fr/grew_match/install/) and invoke
`opam install ocsipersist-dbm` it throws an error trying to link the dependent package `ocsigenserver.5.0.1`:
```
Undefined symbols for architecture x86_64:
  "_SSL_get_peer_certificate", referenced from:
      _ocaml_ssl_get_certificate in libssl_stubs.a(ssl_stubs.o)
```
as detailed in the attached file showing the error as it arises with ocaml 4.13.1. Similar errors result with ocaml 4.14 + ssl 0.5.9 as well as ocaml 4.14 +  ssl 0.5.12.  No errors were reported during installation of `ssl.0.5.9` via opam.

I'm using Command Line Tools for Xcode 13.2 which shows:
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
```
I have the brew package `aspcud` installed at version 1.9.6 as well as `openssl@1.1` which `aspcud` depends on. In the directory `/usr/local/opt/openssl@1.1/lib` there is a library containing the missing symbol
```
nm libssl.a | grep SSL_get_peer_certificate
00000000000024ef T _SSL_get_peer_certificate
```
But apparently the link step for ocsigenserver isn't finding this library. Do I need to somehow need to pass in `-ccopt -L/usr/local/opt/openssl@1.1/lib` ? I don't know how to do that using opam, and maybe that is not the right direction for a solution anyway. I'll be grateful for any tips!

[ocscigenserver-linker-failure-ocaml4.13.txt](https://github.com/grew-nlp/grew/files/9720608/ocscigenserver-linker-failure-ocaml4.13.txt)
[ocscigenserver-linker-failure-ocaml4.14.txt](https://github.com/grew-nlp/grew/files/9720609/ocscigenserver-linker-failure-ocaml4.14.txt)
[4.13-full-command.txt](https://github.com/grew-nlp/grew/files/9720902/4.13-full-command.txt)
[4.14-full-command.txt](https://github.com/grew-nlp/grew/files/9720913/4.14-full-command.txt)

**Comment by bguil** [comment]
Hi,

not sure to understand you problem right now.
But I've also experimented problems on my recent Mac OSX version.

The solution that worked for me is the following:
 * install `ocsipersist-sqlite` instead of `ocsipersist-dbm`
 * Change line 25 in `Makefile.options`from `PERSISTENT_DATA_BACKEND = dbm` to `PERSISTENT_DATA_BACKEND = sqlite`

Let me know if it works for you. I will think about a more robust solution!

**Comment by jthale76** [comment]
I’m not sure what happened but I reinstalled ssl and everything worked from there, I did not need to switch sqlite. This was with ocaml 4.14.  Thanks creating such an awesome corpus search facility! -john

**Comment by bguil** [comment]
Since it works now for you, I close the issue. 
Thanks for the positive feedback!
