### ISSUE TITLE
Connection fail

### ISSUE THREAD

**Issue by Aliwasan** [grew-nlp/grew#21]
Hello,

We have a paper based on GrewMatch researches to deliver to our professor tomorrow. Unfortunately, we cannot work any more on GrewMatch today because of a server failure that is still not solved,it's been more than one hour.
The message is :
Connection fail
The search service is not available.

Thank you to note.
Best rgds

**Comment by bguil** [comment]
I've just restarted the server. It's working now.

I think the problem comes from requests with many nodes containing code like:
```
X1[]; X2[]; X3[]; X4[]; X5[]; X6[]; 
A<<X1; X1<<X2; X2<<X3; X3<<X4; X4<<X5; X5<<X6; X6<<X7; X7<<P
```

I don't know of you are making this request but it is probably the cause of the failure.

**Comment by Aliwasan** [comment]
Désolée d’avoir planté le serveur ! Merci pour l’information, je vais changer de méthode, je me disais aussi que ma requête me semblait pas idéale…
Merci encore 
Alice
