### ISSUE TITLE
Connection fail  The search service is not available.

### ISSUE THREAD

**Issue by Aliwasan** [grew-nlp/grew#22]
Merci de voir ce qui se passe avec le serveur.
Je ne pense pas que ce soit ma requête qui le fasse planter ;)
Merci encore car nous avons un devoir à rendre demain...

**Comment by bguil** [comment]
J'ai redémarré le serveur.
Mais j'ai encore observé des requêtes avec beaucoup de nœuds non reliés, sans doute d'un autre utilisateur.

**Comment by Aliwasan** [comment]
Merci beaucoup, c’est vrai qu’on apprend juste à se servir de Grew-match et on tâtonne un peu…

Merci et encore désolée...

Alice
