### ISSUE TITLE
server fail

### ISSUE THREAD

**Issue by Aliwasan** [grew-nlp/grew#23]
Je me demande si ma requête est problématique car le serveur n'arrête pas de planter : 
je recherche à matcher les phrases où : sous une relation mod@relcl, donc dans une relative, il existe au moins 3 maillons (relations) : m, m1, m2 entre l'antécédent A et le verbe V de la relative.

pattern { A-[mod@relcl]->V; e:V->P; P.PronType=Rel; D[]; m:G->D; A<<G; G<<D; D<<V; D1[]; m1:G1->D1; A<<G1; G1<<D1; D1<<V; D2[]; m2:G2->D2; A<<G2; G2<<D2; D2<<V}

J'avais fait la même requête avec 2 maillons, cela m'avait renvoyé 124 occurrences. Apparemment les autres étudiants ont fait des requêtes avec plusieurs nœuds, je ne sais pas s'ils ont contraint la précédence (<<), y-a-t'il un problème avec ma requête? 

Je suis désolée, mais c'est hyper stressant car on doit rendre un travail demain et j'ai l'impression que je fais planter le serveur à chaque fois... que je déclare ou non les nœuds D, D1, D2...

Merci de votre aide

**Comment by bguil** [comment]
La requête en question pose problème car la contrainte `<<` n'est vérifiée qu'a posteriori

Donc la requête:
```
pattern { 
  A-[mod@relcl]->V; e:V->P; P.PronType=Rel;
  m:G->D; A<<G; G<<D; D<<V;
  m1:G1->D1; A<<G1; G1<<D1; D1<<V;
  m2:G2->D2; A<<G2; G2<<D2; D2<<V
}
```

est cherchée en 2 temps:
```
pattern { 
  A-[mod@relcl]->V; e:V->P; P.PronType=Rel;
  m:G->D; 
  m1:G1->D1; 
  m2:G2->D2; 
}
```
puis les résultats sont filtrés pour respecter l'ordre. Mais la requête sans contrainte a énormément de solution : on peut choisir n'importe quelle relation pour `m`; idem pour `m1` et `m2`, on a donc de l'ordre de $n^3$ relations si $n$ est le nombre de dépendances de la phrase.

**Comment by Aliwasan** [comment]
Merci beaucoup pour votre réponse. Je suis désolée pour le dérangement.

Je (crois que je) comprends s’agissant de la postériorité de la contrainte, cela veut dire qu’une fois qu’il a trouvé les 3 relations, il va filtrer selon l’ordre… à postériori, mais j’ai du mal à comprendre comment il procède exactement. Car il me semble qu’avec la recherche de 2 maillons, il me renvoie un compte juste, mais quand je regarde les phrases j’ai du mal à comprendre comment il matche les précédences. Je vais regarder encore de plus près...

Et s’agissant de la requête sans contrainte je suis bien consciente qu’elle donne lieu à trop de résultats et ne présente pas d’intérêt.

Je vais changer de méthode.

Et surtout je vous remercie pour votre réponse !

Merci encore.

Alice W.
