### ISSUE TITLE
Grew-match not updating

### ISSUE THREAD

**Issue by nschneid** [grew-nlp/grew#30]
http://universal.grew.fr/?custom=638cdf2b9756f says "updated 13 days ago" despite recent updates to the dev branch

**Comment by bguil** [comment]
The continuous integration service behind Grew-match is currently down.
I've manually update EWT. It should be uptodate now.

The next automatic update will depend on the CI service to be back. I will check this.

**Comment by nschneid** [comment]
Hmm, now it says "updated 9 minutes ago" but the changes I pushed aren't reflected....

**Comment by bguil** [comment]
Better with the server restart…
