### ISSUE TITLE
upgrading grew 1.9 -> 1.10 breaks local installation of grew match

### ISSUE THREAD

**Issue by jthale76** [grew-nlp/grew#31]
Hi, I had a local installation of grew match that was working well, but after upgrading "grew" for improved command line tools, now the web interface seems to be busted. I got a "dlopen" error from eliom trying to load a previously compiled gmb.cmxs file.

When I try to remake the backend, I get this error:

john@john-laptop grew_match_back % make
eliomc -ppx -infer -package lwt_ppx -package yojson -package containers -package ANSITerminal -package amr -package conll -package libgrew -package cairo2 -package camomile -package dep2pict -package fileutils gmb_types.eliom
File "gmb_types.eliom", line 33, characters 13-22:
33 |     pattern: Pattern.t;       (* the requested pattern *)
                  ^^^^^^^^^
Error: Unbound module Pattern
make: *** [_server/gmb_types.type_mli] Error 2

I'm presuming some newer version or some related package is needed but I don't understand the ecosystem enough to know which one. Opam reports:

john@john-laptop grew_match_back % opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).

The following packages are not being upgraded because the new versions conflict with other installed packages:
  - cohttp.6.0.0~alpha0
  - cohttp-lwt.6.0.0~alpha0
  - cohttp-lwt-unix.6.0.0~alpha0
    ∗ ocsigenserver.5.0.1 is installed and requires cohttp-lwt-unix < 5.0.0
  - conduit.6.0.1
  - conduit-lwt.6.0.1
  - conduit-lwt-unix.6.0.1
  - ocaml.5.1.0
    ∗ camomile.1.0.2 is installed and requires ocaml (>= 4.02.3 & < 5.0)
    ∗ dune.3.6.1 is installed and requires ocaml < 4.08~~
    ∗ js_of_ocaml-compiler.4.1.0 is installed and requires ocaml (>= 4.04 & < 5.1)
    ∗ ppxlib.0.28.0 is installed and requires ocaml (>= 4.04.1 & < 5.1.0)
  - ocaml-config.3

Grateful for tips about *which* constraint to relax...

**Comment by bguil** [comment]
The tool `grew_match_back` is not delivered by opam. You have to update it independently.

A `git pull` in the `grew_match_back` folder should be enough.
And a `git pull` in `grew_match` also for the front-end.

Else, you can find a dockerfile provided by @jheinecke: https://github.com/jheinecke/grewmatchdocker which is based on the last version of the tool.

**Comment by jthale76** [comment]
beautiful. je vous remercie enormement....
