### ISSUE TITLE
ANSITerminal dependency missing

### ISSUE THREAD

**Issue by flareau** [grew-nlp/grew#38]
When installing grew, I get this error:

        ### output ###
        # File "src/dune", line 26, characters 4-16:
        # 26 |     ANSITerminal 
        #          ^^^^^^^^^^^^
        # Error: Library "ANSITerminal" not found.
        # -> required by library "grewlib" in _build/default/src
        # -> required by _build/default/META.grewlib
        # -> required by _build/install/default/lib/grewlib/META
        # -> required by _build/default/grewlib.install
        # -> required by alias install

Installing the ANSITerminal library with `opam install ANSITerminal` first and then installing grew solves the problem.

**Comment by bguil** [comment]
Thanks for reporting. The missing dependency was added. It will be available in the next release.
