### ISSUE TITLE
Grew match service is down

### ISSUE THREAD

**Issue by Ingerid** [grew-nlp/grew#39]
I noticed last week that Grew-match was down, and it is still only showing this page:

![image](https://user-images.githubusercontent.com/37677043/234215384-9de1eb0d-fb04-490e-81d0-ed4dc20d2f31.png)

I am connected to eduroam-wifi.
Browser: Firefox version 112 
Platform: Ubuntu 22.04.2 LTS

**Comment by s-herrera** [comment]
Just to add some information, http version is working well.

**Comment by bguil** [comment]
I confirm that http://universal.grew.fr is ok (but https is not).

But https should be valid. I will change this ASAP.
I will close the issue when it's done.

**Comment by bguil** [comment]
https://universal.grew.fr is now available. 

It should have been done long ago!
