### ISSUE TITLE
Problem with the SUD 2.12 treebanks that have EUD version

### ISSUE THREAD

**Issue by s-herrera** [grew-nlp/grew#40]
Hi,
It seems there is a problem on Grew-Match with the SUD 2.12 treebanks coming from UD that have a EUD version.

![image](https://github.com/grew-nlp/grew/assets/95502001/81e18db9-ac0b-4fd1-8cae-3081306ef378)

**Comment by bguil** [comment]
Thanks for reporting. This should be fixed now.
