### ISSUE TITLE
Search within a subcorpus file?

### ISSUE THREAD

**Issue by nschneid** [grew-nlp/grew#41]
Is it possible to restrict a UD treebank query to a particular file, e.g. the training set only?

**Comment by bguil** [comment]
This is not currently possible, except if you can describe the `sent_id` of a sentence from the train file as a regexp. For instance in French-GSD, the condition below would filter sentence from train only:
```
global { sent_id = re"fr-ud-train.*" }
```

But, it this can be useful, it would be easy to add a pseudo sentence metadata like `# filename = train.conllu` at compile time.

**Comment by nschneid** [comment]
> But, it this can be useful, it would be easy to add a pseudo sentence metadata like `# filename = train.conllu` at compile time.

That would be excellent! English-EWT, for example, doesn't have any indication of the file in the sentence-level metadata.

**Comment by bguil** [comment]
It's available (only on English-EWT right now). The metadata is named `_filename` to avoid confusion with real CoNLLU metadata.
For a request on train only:
```
global { _filename = "en_ewt-ud-train.conllu" }
```
An example: [upos INTJ in train only](https://universal.grew.fr/?custom=647bae7c1eb88).

It will be available on other treebanks later.

**Comment by nschneid** [comment]
Thanks! This saves me a lot of time.
