### ISSUE TITLE
increase timeout

### ISSUE THREAD

**Issue by jthale76** [grew-nlp/grew#42]
I am getting the Timeout message searching large dependency corpora on a local installation of grew-match. How can I examine or increase the threshold until timeout?

**Comment by bguil** [comment]
The timeout value is defined here: https://gitlab.inria.fr/grew/grew_match_back/-/blob/master/gmb_global.eliom.
You have to change it in the code. But, it would be nice to have a more user-friendly way to change this! It should be added.
