### ISSUE TITLE
Error message when many results are found

### ISSUE THREAD

**Issue by simon-clematide** [grew-nlp/grew#46]
When searching for frequent constructions in a German Treebank, the following error message appears:

![image](https://github.com/grew-nlp/grew/assets/3041168/2be45678-38a7-4447-a569-5f553e940751)

It works normally when searching for a rare UPOS such as INTJ.

**Comment by bguil** [comment]
Does the bug appear today or do you have seen it before?

**Comment by bguil** [comment]
I've reverted a change done this morning. It should be ok now.

**Comment by simon-clematide** [comment]
Yes, works now for me. Thanks a lot for the quick fix!
