### ISSUE TITLE
disjunction between two attributes

### ISSUE THREAD

**Issue by cinkova** [grew-nlp/grew#47]
Dear developers, how can I ask for a node that either has upos=NOUN or feature value Possessive=Yes? The documentation mentions only disjunctions between values of the same attribute, and the options at hand just do not work for me.

**Comment by bguil** [comment]
This is now available in the last version (1.14) of Grew (see [doc](https://grew.fr/doc/request/#disjunction-in-node-clause)) and in Grew-match.
A disjunction can be used to describe a node, using the `|` symbol.

For instance, the following request corresponds to what you asked:
```
pattern { N [upos=NOUN]|[Possessive=Yes] }
```
[Run the request on `UD_Maghrebi_Arabic_French-Arabizi@2.12`](https://universal.grew.fr/?custom=654ff86bc5ae2) (the only treebank in 2.12 using feature `Possessive=Yes`).
