### ISSUE TITLE
Grew installation problem

### ISSUE THREAD

**Issue by GusSampaio** [grew-nlp/grew#48]
Hey, someone could help me with this?

Following the steps found on grerw installation tutorial (https://grew.fr/usage/install/) I faced this error:

$ opam install grew
The following actions will be performed:
  ∗ install grewlib 1.16.0 [required by grew]
  ∗ install grew    1.16.0
===== ∗ 2 =====

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved grew.1.16.0  (cached)
⬇ retrieved grewlib.1.16.0  (cached)
[ERROR] The compilation of grewlib.1.16.0 failed at "dune build -p grewlib -j 7 @install".

#=== ERROR while compiling grewlib.1.16.0 =====================================#
# context     2.1.2 | linux/x86_64 | ocaml.4.13.1 | http://opam.grew.fr#2024-06-02 14:44
# path        ~/.opam/default/.opam-switch/build/grewlib.1.16.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p grewlib -j 7 @install
# exit-code   1
# env-file    ~/.opam/log/grewlib-10578-47c886.env
# output-file ~/.opam/log/grewlib-10578-47c886.out
### output ###
# File "src/dune", line 26, characters 4-6:
# 26 |     re
#          ^^
# Error: Library "re" not found.
# -> required by library "grewlib" in _build/default/src
# -> required by _build/default/META.grewlib
# -> required by _build/install/default/lib/grewlib/META
# -> required by _build/default/grewlib.install
# -> required by alias install

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build grewlib 1.16.0
└─
╶─ No changes have been performed

It seems to have a problem with the regex library but I have no idea how to fix it.

**Comment by bguil** [comment]
It seems that a dependency is missing.
Can you try: `opam install re` before Grew installation?

**Comment by GusSampaio** [comment]
Yes! That worked. Thanks a lot.

I'm working on a research project at Universidade of São Paulo using to adapt grew's use to enhaced universal dependencies on portguese brazilian language. Call me on gustavo.sampaio@usp.br if you want to know how is the project going.

**Comment by bguil** [comment]
Thanks for the feedback. In the meantime, I've released a new version `1.16.1` which fixes the bug.
