### ISSUE TITLE
"last updated" stuck on 2022/01/09

### ISSUE THREAD

**Issue by nschneid** [grew-nlp/grew#5]
Some of the UD_English-EWT updates I pushed this morning are now incorporated into [these search results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61e313623cb78), so I would expect the date to say today. (Also, it would be great to see the *time* of the last update!)

**Comment by bguil** [comment]
Thanks for reporting.
It was a cache problem. I hope that it is fixed now.
I will add update *time* soon.

**Comment by bguil** [comment]
With the new version of Grew-match, I've added a message *update xx hours ago* to avoid to deal with timezones.
