### ISSUE TITLE
[Grew-transform] Error when using underscore in concept name

### ISSUE THREAD

**Issue by siyanapavlova** [grew-nlp/grew#7]
Grew-transform throws an error when underscores are used in concept names (in PropBank those are the predicates for phrasal verbs).

E.g., I get an error `Bad char: _` for the line containing `bring_about.05` for the example below. No issue when the underscore is removed. The underscores in "World_War_I" are not a problem.

```
# ::snt The First World War brought about shifts [...].
# ::id w02012042
(b / bring_about.05
    :ARG0 (w /war
        :wiki "World_War_I"
        :name (n / name
            :op1 "First"
            :op2 "World"
            :op3 "War"
        )
    )
    :ARG1 (s /shift)
)

```

**Comment by bguil** [comment]
This is fixed in the online tool (the symbol `_` is now accepted in identifiers).

For a local usage of `grew transform`, an update is needed with:

```
opam update
opam upgrade libcaml-amr
```
